// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wyvern.Infrastructure.Data;

#nullable disable

namespace Wyvern.Infrastructure.Migrations
{
    [DbContext(typeof(WyvernDbContext))]
    [Migration("20260403054301_atualizaClassePlayer")]
    partial class atualizaClassePlayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wyvern.Domain.Entities.Atributo", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("Carisma")
                        .HasColumnType("int");

                    b.Property<int>("Constituicao")
                        .HasColumnType("int");

                    b.Property<int>("Destreza")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<int>("Sabedoria")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.ToTable("Atributos");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Campanha", b =>
                {
                    b.Property<int>("CampanhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampanhaId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("MestreId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CampanhaId");

                    b.HasIndex("MestreId");

                    b.ToTable("Campanhas");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Magia", b =>
                {
                    b.Property<int>("MagiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MagiaId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MagiaId");

                    b.ToTable("Magias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Pericia", b =>
                {
                    b.Property<int>("PericiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PericiaId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PericiaId");

                    b.ToTable("Pericias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Personagem", b =>
                {
                    b.Property<int>("PersonagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonagemId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonagemPlayerPersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("PersonagemPlayerPersonagemId");

                    b.HasIndex("TipoId");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemCombate", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("ClasseArmadura")
                        .HasColumnType("int");

                    b.Property<int>("Deslocamento")
                        .HasColumnType("int");

                    b.Property<int>("Iniciativa")
                        .HasColumnType("int");

                    b.Property<int>("VidaAtual")
                        .HasColumnType("int");

                    b.Property<int>("VidaMaxima")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemCombates");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemItem", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("PersonagemItens");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemMagia", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("MagiaId")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId", "MagiaId");

                    b.HasIndex("MagiaId");

                    b.ToTable("PersonagemMagias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPericia", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("PericiaId")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<bool>("Proficiente")
                        .HasColumnType("bit");

                    b.HasKey("PersonagemId", "PericiaId");

                    b.HasIndex("PericiaId");

                    b.ToTable("PersonagemPericias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPlayer", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<string>("Alinhamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemPlayers");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Sessao", b =>
                {
                    b.Property<int>("SessaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessaoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSessao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroSessao")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessaoId");

                    b.HasIndex("CampanhaId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.TipoPersonagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoPersonagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Atributo", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("Atributo")
                        .HasForeignKey("Wyvern.Domain.Entities.Atributo", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Campanha", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Usuario", "Mestre")
                        .WithMany("Campanhas")
                        .HasForeignKey("MestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mestre");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Personagem", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.PersonagemPlayer", "PersonagemPlayer")
                        .WithMany()
                        .HasForeignKey("PersonagemPlayerPersonagemId");

                    b.HasOne("Wyvern.Domain.Entities.TipoPersonagem", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("CriadoPor");

                    b.Navigation("PersonagemPlayer");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemCombate", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne()
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemCombate", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemItem", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemItens")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemMagia", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Magia", "Magia")
                        .WithMany()
                        .HasForeignKey("MagiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemMagias")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magia");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPericia", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Pericia", "Pericia")
                        .WithMany()
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany()
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pericia");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPlayer", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "personagem")
                        .WithOne()
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemPlayer", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Sessao", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Campanha", "Campanha")
                        .WithMany("Sessoes")
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Campanha", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Personagem", b =>
                {
                    b.Navigation("Atributo")
                        .IsRequired();

                    b.Navigation("PersonagemItens");

                    b.Navigation("PersonagemMagias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Campanhas");
                });
#pragma warning restore 612, 618
        }
    }
}
