// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wyvern.Infrastructure.Data;

#nullable disable

namespace Wyvern.Infrastructure.Migrations
{
    [DbContext(typeof(WyvernDbContext))]
    [Migration("20260717135944_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Wyvern.Domain.Entities.Anotacao", b =>
                {
                    b.Property<int>("AnotacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublica")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PastaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("AnotacaoId");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("PastaId");

                    b.ToTable("Anotacoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Atributo", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constituicao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Destreza")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Forca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProficienciaSalvaguardaCarisma")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProficienciaSalvaguardaConstituicao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProficienciaSalvaguardaDestreza")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProficienciaSalvaguardaForca")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProficienciaSalvaguardaInteligencia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProficienciaSalvaguardaSabedoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sabedoria")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemId");

                    b.ToTable("Atributos");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Campanha", b =>
                {
                    b.Property<int>("CampanhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("MestreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenConvite")
                        .HasColumnType("TEXT");

                    b.HasKey("CampanhaId");

                    b.HasIndex("MestreId");

                    b.ToTable("Campanhas");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.CampanhaJogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntrouEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Campanhas_Jogadores");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Combate", b =>
                {
                    b.Property<int>("CombateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("RodadaAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TurnoAtualIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("CombateId");

                    b.HasIndex("SessaoId");

                    b.ToTable("Combates");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.CombateParticipante", b =>
                {
                    b.Property<int>("ParticipanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseArmadura")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CombateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condicoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FalhasMorte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Iniciativa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInimigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeNPC")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SucessosMorte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaMaxima")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParticipanteId");

                    b.HasIndex("CombateId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("CombateParticipantes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Magia", b =>
                {
                    b.Property<int>("MagiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MagiaId");

                    b.ToTable("Magias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PastaAnotacao", b =>
                {
                    b.Property<int>("PastaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublica")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PastaId");

                    b.HasIndex("CampanhaId");

                    b.ToTable("PastasAnotacao");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Pericia", b =>
                {
                    b.Property<int>("PericiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PericiaId");

                    b.ToTable("Pericias");

                    b.HasData(
                        new
                        {
                            PericiaId = 1,
                            Ativo = true,
                            Nome = "Acrobacia"
                        },
                        new
                        {
                            PericiaId = 2,
                            Ativo = true,
                            Nome = "Arcanismo"
                        },
                        new
                        {
                            PericiaId = 3,
                            Ativo = true,
                            Nome = "Atletismo"
                        },
                        new
                        {
                            PericiaId = 4,
                            Ativo = true,
                            Nome = "Atuação"
                        },
                        new
                        {
                            PericiaId = 5,
                            Ativo = true,
                            Nome = "Enganação"
                        },
                        new
                        {
                            PericiaId = 6,
                            Ativo = true,
                            Nome = "Furtividade"
                        },
                        new
                        {
                            PericiaId = 7,
                            Ativo = true,
                            Nome = "História"
                        },
                        new
                        {
                            PericiaId = 8,
                            Ativo = true,
                            Nome = "Intimidação"
                        },
                        new
                        {
                            PericiaId = 9,
                            Ativo = true,
                            Nome = "Intuição"
                        },
                        new
                        {
                            PericiaId = 10,
                            Ativo = true,
                            Nome = "Investigação"
                        },
                        new
                        {
                            PericiaId = 11,
                            Ativo = true,
                            Nome = "Lidar com Animais"
                        },
                        new
                        {
                            PericiaId = 12,
                            Ativo = true,
                            Nome = "Medicina"
                        },
                        new
                        {
                            PericiaId = 13,
                            Ativo = true,
                            Nome = "Natureza"
                        },
                        new
                        {
                            PericiaId = 14,
                            Ativo = true,
                            Nome = "Percepção"
                        },
                        new
                        {
                            PericiaId = 15,
                            Ativo = true,
                            Nome = "Persuasão"
                        },
                        new
                        {
                            PericiaId = 16,
                            Ativo = true,
                            Nome = "Prestidigitação"
                        },
                        new
                        {
                            PericiaId = 17,
                            Ativo = true,
                            Nome = "Religião"
                        },
                        new
                        {
                            PericiaId = 18,
                            Ativo = true,
                            Nome = "Sobrevivência"
                        });
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Personagem", b =>
                {
                    b.Property<int>("PersonagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemId");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("TipoId");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemAcaoBonus", b =>
                {
                    b.Property<int>("PersonagemAcaoBonusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemAcaoBonusId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemAcoesBonus");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemAcaoLendaria", b =>
                {
                    b.Property<int>("PersonagemAcaoLendariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustoAcao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemAcaoLendariaId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemAcoesLendarias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemAcaoPadrao", b =>
                {
                    b.Property<int>("PersonagemAcaoPadraoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alcance")
                        .HasColumnType("TEXT");

                    b.Property<string>("AtributoBase")
                        .HasColumnType("TEXT");

                    b.Property<int>("BonusAcerto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dano")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Proficiente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Propriedades")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDano")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonagemAcaoPadraoId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemAcoesPadrao");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemAtaque", b =>
                {
                    b.Property<int>("PersonagemAtaqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alcance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtributoBase")
                        .HasColumnType("TEXT");

                    b.Property<int>("BonusAcerto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dano")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Proficiente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Propriedades")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDano")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonagemAtaqueId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemAtaques");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemCombate", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseArmadura")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClasseArmaduraEscudo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DadoVidaGasto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DadoVidaMaximo")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeathSaveFalhas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeathSaveSucessos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deslocamento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Iniciativa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InspiracaoHeroica")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProficienciaBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaTemporaria")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemCombates");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemConjuracao", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtributoConjuracao")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotsNivel1Atual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel1Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel2Atual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel2Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel3Atual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel3Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel4Atual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel4Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel5Atual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel5Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel6Atual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel6Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel7Atual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel7Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel8Atual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel8Max")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel9Atual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotsNivel9Max")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemConjuracoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemDetalhes", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aparencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaracteristicasClasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoriaPersonalidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Idiomas")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProficienciaArmaduraLeve")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProficienciaArmaduraMedia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProficienciaArmaduraPesada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProficienciaArmas")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ProficienciaEscudos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProficienciaFerramentas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Talentos")
                        .HasColumnType("TEXT");

                    b.Property<string>("TracosEspecie")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemDetalhes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemDinheiro", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PL")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PP")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemDinheiros");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemItem", b =>
                {
                    b.Property<int>("PersonagemItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Raridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PersonagemItemId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemItens");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemMagia", b =>
                {
                    b.Property<int>("PersonagemMagiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Escola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Material")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Somatico")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Verbal")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemMagiaId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemMagias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemNpc", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnotacoesLivres")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoriaUso")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormulaDadoVida")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImunidadesCondicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImunidadesDano")
                        .HasColumnType("TEXT");

                    b.Property<string>("NivelDesafio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resistencias")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegredosFaccoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sentidos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tamanho")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tendencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCriatura")
                        .HasColumnType("TEXT");

                    b.Property<string>("VinculosIdeais")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vulnerabilidades")
                        .HasColumnType("TEXT");

                    b.Property<int>("XpConcedido")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagensNpc");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPericia", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PericiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bonus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Proficiente")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemId", "PericiaId");

                    b.HasIndex("PericiaId");

                    b.ToTable("PersonagemPericias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPlayer", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alinhamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Antecedente")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subclasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tamanho")
                        .HasColumnType("TEXT");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemPlayers");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemReacao", b =>
                {
                    b.Property<int>("PersonagemReacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gatilho")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemReacaoId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemReacoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemTracoEspecial", b =>
                {
                    b.Property<int>("PersonagemTracoEspecialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonagemTracoEspecialId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemTracosEspeciais");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Sessao", b =>
                {
                    b.Property<int>("SessaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAgendada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSessao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroSessao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SessaoId");

                    b.HasIndex("CampanhaId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.TipoPersonagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TipoPersonagem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Jogador"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "NPC"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Monstro"
                        });
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Anotacao", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wyvern.Domain.Entities.PastaAnotacao", "Pasta")
                        .WithMany("Anotacoes")
                        .HasForeignKey("PastaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Campanha");

                    b.Navigation("CriadoPor");

                    b.Navigation("Pasta");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Atributo", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("Atributo")
                        .HasForeignKey("Wyvern.Domain.Entities.Atributo", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Campanha", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Usuario", "Mestre")
                        .WithMany("Campanhas")
                        .HasForeignKey("MestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mestre");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.CampanhaJogador", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Campanha", "Campanha")
                        .WithMany("Jogadores")
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Combate", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.CombateParticipante", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Combate", "Combate")
                        .WithMany("Participantes")
                        .HasForeignKey("CombateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany()
                        .HasForeignKey("PersonagemId");

                    b.Navigation("Combate");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PastaAnotacao", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Personagem", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.TipoPersonagem", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("CriadoPor");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemAcaoBonus", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemAcoesBonus")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemAcaoLendaria", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemAcoesLendarias")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemAcaoPadrao", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemAcoesPadrao")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemAtaque", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemAtaques")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemCombate", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("PersonagemCombate")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemCombate", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemConjuracao", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("PersonagemConjuracao")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemConjuracao", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemDetalhes", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("PersonagemDetalhes")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemDetalhes", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemDinheiro", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("PersonagemDinheiro")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemDinheiro", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemItem", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemItens")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemMagia", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemMagias")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemNpc", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("PersonagemNpc")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemNpc", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPericia", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Pericia", "Pericia")
                        .WithMany()
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemPericias")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pericia");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPlayer", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "personagem")
                        .WithOne("PersonagemPlayer")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemPlayer", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemReacao", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemReacoes")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemTracoEspecial", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemTracosEspeciais")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Sessao", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Campanha", "Campanha")
                        .WithMany("Sessoes")
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Campanha", b =>
                {
                    b.Navigation("Jogadores");

                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Combate", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PastaAnotacao", b =>
                {
                    b.Navigation("Anotacoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Personagem", b =>
                {
                    b.Navigation("Atributo")
                        .IsRequired();

                    b.Navigation("PersonagemAcoesBonus");

                    b.Navigation("PersonagemAcoesLendarias");

                    b.Navigation("PersonagemAcoesPadrao");

                    b.Navigation("PersonagemAtaques");

                    b.Navigation("PersonagemCombate");

                    b.Navigation("PersonagemConjuracao");

                    b.Navigation("PersonagemDetalhes");

                    b.Navigation("PersonagemDinheiro");

                    b.Navigation("PersonagemItens");

                    b.Navigation("PersonagemMagias");

                    b.Navigation("PersonagemNpc");

                    b.Navigation("PersonagemPericias");

                    b.Navigation("PersonagemPlayer");

                    b.Navigation("PersonagemReacoes");

                    b.Navigation("PersonagemTracosEspeciais");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Campanhas");
                });
#pragma warning restore 612, 618
        }
    }
}
