// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wyvern.Infrastructure.Data;

#nullable disable

namespace Wyvern.Infrastructure.Migrations
{
    [DbContext(typeof(WyvernDbContext))]
    [Migration("20260714131611_AddDescricaoToItem")]
    partial class AddDescricaoToItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wyvern.Domain.Entities.Atributo", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("Carisma")
                        .HasColumnType("int");

                    b.Property<int>("Constituicao")
                        .HasColumnType("int");

                    b.Property<int>("Destreza")
                        .HasColumnType("int");

                    b.Property<int>("Forca")
                        .HasColumnType("int");

                    b.Property<int>("Inteligencia")
                        .HasColumnType("int");

                    b.Property<bool>("ProficienciaSalvaguardaCarisma")
                        .HasColumnType("bit");

                    b.Property<bool>("ProficienciaSalvaguardaConstituicao")
                        .HasColumnType("bit");

                    b.Property<bool>("ProficienciaSalvaguardaDestreza")
                        .HasColumnType("bit");

                    b.Property<bool>("ProficienciaSalvaguardaForca")
                        .HasColumnType("bit");

                    b.Property<bool>("ProficienciaSalvaguardaInteligencia")
                        .HasColumnType("bit");

                    b.Property<bool>("ProficienciaSalvaguardaSabedoria")
                        .HasColumnType("bit");

                    b.Property<int>("Sabedoria")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.ToTable("Atributos");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Campanha", b =>
                {
                    b.Property<int>("CampanhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampanhaId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("MestreId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CampanhaId");

                    b.HasIndex("MestreId");

                    b.ToTable("Campanhas");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Magia", b =>
                {
                    b.Property<int>("MagiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MagiaId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MagiaId");

                    b.ToTable("Magias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Pericia", b =>
                {
                    b.Property<int>("PericiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PericiaId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PericiaId");

                    b.ToTable("Pericias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Personagem", b =>
                {
                    b.Property<int>("PersonagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonagemId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.HasIndex("CampanhaId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("TipoId");

                    b.ToTable("Personagens");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemAtaque", b =>
                {
                    b.Property<int>("PersonagemAtaqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonagemAtaqueId"));

                    b.Property<string>("Alcance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BonusAcerto")
                        .HasColumnType("int");

                    b.Property<string>("Dano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<string>("Propriedades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDano")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonagemAtaqueId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemAtaques");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemCombate", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("ClasseArmadura")
                        .HasColumnType("int");

                    b.Property<int>("ClasseArmaduraEscudo")
                        .HasColumnType("int");

                    b.Property<int>("DadoVidaGasto")
                        .HasColumnType("int");

                    b.Property<string>("DadoVidaMaximo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeathSaveFalhas")
                        .HasColumnType("int");

                    b.Property<int>("DeathSaveSucessos")
                        .HasColumnType("int");

                    b.Property<int>("Deslocamento")
                        .HasColumnType("int");

                    b.Property<int>("Iniciativa")
                        .HasColumnType("int");

                    b.Property<bool>("InspiracaoHeroica")
                        .HasColumnType("bit");

                    b.Property<int>("VidaAtual")
                        .HasColumnType("int");

                    b.Property<int>("VidaMaxima")
                        .HasColumnType("int");

                    b.Property<int>("VidaTemporaria")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemCombates");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemConjuracao", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<string>("AtributoConjuracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CdMagia")
                        .HasColumnType("int");

                    b.Property<int>("ModificadorAtaqueMagico")
                        .HasColumnType("int");

                    b.Property<int>("ModificadorConjuracao")
                        .HasColumnType("int");

                    b.Property<int>("SlotsGastosNivel1")
                        .HasColumnType("int");

                    b.Property<int>("SlotsGastosNivel2")
                        .HasColumnType("int");

                    b.Property<int>("SlotsGastosNivel3")
                        .HasColumnType("int");

                    b.Property<int>("SlotsGastosNivel4")
                        .HasColumnType("int");

                    b.Property<int>("SlotsGastosNivel5")
                        .HasColumnType("int");

                    b.Property<int>("SlotsGastosNivel6")
                        .HasColumnType("int");

                    b.Property<int>("SlotsGastosNivel7")
                        .HasColumnType("int");

                    b.Property<int>("SlotsGastosNivel8")
                        .HasColumnType("int");

                    b.Property<int>("SlotsGastosNivel9")
                        .HasColumnType("int");

                    b.Property<int>("SlotsTotalNivel1")
                        .HasColumnType("int");

                    b.Property<int>("SlotsTotalNivel2")
                        .HasColumnType("int");

                    b.Property<int>("SlotsTotalNivel3")
                        .HasColumnType("int");

                    b.Property<int>("SlotsTotalNivel4")
                        .HasColumnType("int");

                    b.Property<int>("SlotsTotalNivel5")
                        .HasColumnType("int");

                    b.Property<int>("SlotsTotalNivel6")
                        .HasColumnType("int");

                    b.Property<int>("SlotsTotalNivel7")
                        .HasColumnType("int");

                    b.Property<int>("SlotsTotalNivel8")
                        .HasColumnType("int");

                    b.Property<int>("SlotsTotalNivel9")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemConjuracoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemDetalhes", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<string>("Aparencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaracteristicasClasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoriaPersonalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idiomas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProficienciaArmaduraLeve")
                        .HasColumnType("bit");

                    b.Property<bool>("ProficienciaArmaduraMedia")
                        .HasColumnType("bit");

                    b.Property<bool>("ProficienciaArmaduraPesada")
                        .HasColumnType("bit");

                    b.Property<string>("ProficienciaArmas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProficienciaEscudos")
                        .HasColumnType("bit");

                    b.Property<string>("ProficienciaFerramentas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Talentos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TracosEspecie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemDetalhes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemDinheiro", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("PC")
                        .HasColumnType("int");

                    b.Property<int>("PE")
                        .HasColumnType("int");

                    b.Property<int>("PL")
                        .HasColumnType("int");

                    b.Property<int>("PO")
                        .HasColumnType("int");

                    b.Property<int>("PP")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemDinheiros");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemItem", b =>
                {
                    b.Property<int>("PersonagemItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonagemItemId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<string>("Raridade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonagemItemId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemItens");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemMagia", b =>
                {
                    b.Property<int>("PersonagemMagiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonagemMagiaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Escola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Material")
                        .HasColumnType("bit");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<bool>("Somatico")
                        .HasColumnType("bit");

                    b.Property<bool>("Verbal")
                        .HasColumnType("bit");

                    b.HasKey("PersonagemMagiaId");

                    b.HasIndex("PersonagemId");

                    b.ToTable("PersonagemMagias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPericia", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<int>("PericiaId")
                        .HasColumnType("int");

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<bool>("Proficiente")
                        .HasColumnType("bit");

                    b.HasKey("PersonagemId", "PericiaId");

                    b.HasIndex("PericiaId");

                    b.ToTable("PersonagemPericias");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPlayer", b =>
                {
                    b.Property<int>("PersonagemId")
                        .HasColumnType("int");

                    b.Property<string>("Alinhamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Antecedente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subclasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tamanho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("PersonagemId");

                    b.ToTable("PersonagemPlayers");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Sessao", b =>
                {
                    b.Property<int>("SessaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessaoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("CampanhaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSessao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroSessao")
                        .HasColumnType("int");

                    b.Property<string>("Obs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessaoId");

                    b.HasIndex("CampanhaId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.TipoPersonagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoPersonagem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Jogador"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "NPC"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Monstro"
                        });
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Atributo", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("Atributo")
                        .HasForeignKey("Wyvern.Domain.Entities.Atributo", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Campanha", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Usuario", "Mestre")
                        .WithMany("Campanhas")
                        .HasForeignKey("MestreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mestre");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Personagem", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.TipoPersonagem", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("CriadoPor");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemAtaque", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemAtaques")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemCombate", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("PersonagemCombate")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemCombate", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemConjuracao", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("PersonagemConjuracao")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemConjuracao", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemDetalhes", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("PersonagemDetalhes")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemDetalhes", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemDinheiro", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithOne("PersonagemDinheiro")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemDinheiro", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemItem", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemItens")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemMagia", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemMagias")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPericia", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Pericia", "Pericia")
                        .WithMany()
                        .HasForeignKey("PericiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wyvern.Domain.Entities.Personagem", "Personagem")
                        .WithMany("PersonagemPericias")
                        .HasForeignKey("PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pericia");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.PersonagemPlayer", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Personagem", "personagem")
                        .WithOne("PersonagemPlayer")
                        .HasForeignKey("Wyvern.Domain.Entities.PersonagemPlayer", "PersonagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("personagem");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Sessao", b =>
                {
                    b.HasOne("Wyvern.Domain.Entities.Campanha", "Campanha")
                        .WithMany("Sessoes")
                        .HasForeignKey("CampanhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Campanha", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Personagem", b =>
                {
                    b.Navigation("Atributo")
                        .IsRequired();

                    b.Navigation("PersonagemAtaques");

                    b.Navigation("PersonagemCombate");

                    b.Navigation("PersonagemConjuracao");

                    b.Navigation("PersonagemDetalhes");

                    b.Navigation("PersonagemDinheiro");

                    b.Navigation("PersonagemItens");

                    b.Navigation("PersonagemMagias");

                    b.Navigation("PersonagemPericias");

                    b.Navigation("PersonagemPlayer");
                });

            modelBuilder.Entity("Wyvern.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Campanhas");
                });
#pragma warning restore 612, 618
        }
    }
}
